//Client file generated by RPC Compiler.
import { Injectable } from '@angular/core';
import { Http, Response } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { Observer } from 'rxjs/Observer';
import { Deserialize, Converter } from 'Serializable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import {rpcService, rpcMember, ITaskHost, TaskInfo} from 'Serializable';

import {Dog} from '../app/dog';
@Injectable()
export class NCBIMethods {
	constructor(private $_Angular2HttpClient: Http){
	}
	public test(): Observable<string>{
		return this.$_Angular2HttpClient.post('/ncbi/ncbi.rpc.js?NCBIMethods-test', []).map(Converter.convertStringResponse);
	}
	public dogs(): Observable< Dog[]>{
		return Observable.create((observer: Observer< Dog[]>) => {
			this.$_Angular2HttpClient.post('/ncbi/ncbi.rpc.js?NCBIMethods-dogs', []).map(Converter.convertStringResponse).subscribe(stringValue => {
				console.log("stringValue: ", stringValue);
				if(stringValue){
					let jsonObject = JSON.parse(stringValue);
					Deserialize(jsonObject, (deserialized) => {
						observer.next(deserialized);
						observer.complete();
					});
				}
				else{
					observer.next(null);
					observer.complete();
				}
			});
		});
	}
	public log(dog:  Dog): Observable<any>{
		return Observable.create((observer: Observer<any>) => {
			this.$_Angular2HttpClient.post('/ncbi/ncbi.rpc.js?NCBIMethods-log', [dog]).map(Converter.convertStringResponse).subscribe(stringValue => {
				console.log("stringValue: ", stringValue);
				if(stringValue){
					let jsonObject = JSON.parse(stringValue);
					Deserialize(jsonObject, (deserialized) => {
						observer.next(deserialized);
						observer.complete();
					});
				}
				else{
					observer.next(null);
					observer.complete();
				}
			});
		});
	}
	public search(keywords:  string, limit:  number): Observable< TaskInfo>{
		return Observable.create((observer: Observer< TaskInfo>) => {
			this.$_Angular2HttpClient.post('/ncbi/ncbi.rpc.js?NCBIMethods-search', [keywords, limit]).map(Converter.convertStringResponse).subscribe(stringValue => {
				console.log("stringValue: ", stringValue);
				if(stringValue){
					let jsonObject = JSON.parse(stringValue);
					Deserialize(jsonObject, (deserialized) => {
						observer.next(deserialized);
						observer.complete();
					});
				}
				else{
					observer.next(null);
					observer.complete();
				}
			});
		});
	}
}
