"use strict";
var mime;
(function (mime_1) {
    function lookup(path) {
        return MimeTypes.filter(function (mime) {
            return mime.extensions.some(function (ext) {
                ext.lastIndex = -1;
                return ext.test(path);
            });
        });
    }
    mime_1.lookup = lookup;
    var MimeTypes = [
        { title: "3D Crossword Plugin", MIME: "application/vnd.hzn-3d-crossword", extensions: [/\.x3d$/] },
        { title: "3GP", MIME: "video/3gpp", extensions: [/\.3gp$/] },
        { title: "3GP2", MIME: "video/3gpp2", extensions: [/\.3g2$/] },
        { title: "3GPP MSEQ File", MIME: "application/vnd.mseq", extensions: [/\.mseq$/] },
        { title: "3M Post It Notes", MIME: "application/vnd.3m.post-it-notes", extensions: [/\.pwn$/] },
        { title: "3rd Generation Partnership Project - Pic Large", MIME: "application/vnd.3gpp.pic-bw-large", extensions: [/\.plb$/] },
        { title: "3rd Generation Partnership Project - Pic Small", MIME: "application/vnd.3gpp.pic-bw-small", extensions: [/\.psb$/] },
        { title: "3rd Generation Partnership Project - Pic Var", MIME: "application/vnd.3gpp.pic-bw-var", extensions: [/\.pvb$/] },
        { title: "3rd Generation Partnership Project - Transaction Capabilities Application Part", MIME: "application/vnd.3gpp2.tcap", extensions: [/\.tcap$/] },
        { title: "7-Zip", MIME: "application/x-7z-compressed", extensions: [/\.7z$/] },
        { title: "AbiWord", MIME: "application/x-abiword", extensions: [/\.abw$/] },
        { title: "Ace Archive", MIME: "application/x-ace-compressed", extensions: [/\.ace$/] },
        { title: "Active Content Compression", MIME: "application/vnd.americandynamics.acc", extensions: [/\.acc$/] },
        { title: "ACU Cobol", MIME: "application/vnd.acucobol", extensions: [/\.acu$/] },
        { title: "ACU Cobol", MIME: "application/vnd.acucorp", extensions: [/\.atc$/] },
        { title: "Adaptive differential pulse-code modulation", MIME: "audio/adpcm", extensions: [/\.adp$/] },
        { title: "Adobe (Macropedia) Authorware - Binary File", MIME: "application/x-authorware-bin", extensions: [/\.aab$/] },
        { title: "Adobe (Macropedia) Authorware - Map", MIME: "application/x-authorware-map", extensions: [/\.aam$/] },
        { title: "Adobe (Macropedia) Authorware - Segment File", MIME: "application/x-authorware-seg", extensions: [/\.aas$/] },
        { title: "Adobe AIR Application", MIME: "application/vnd.adobe.air-application-installer-package+zip", extensions: [/\.air$/] },
        { title: "Adobe Flash", MIME: "application/x-shockwave-flash", extensions: [/\.swf$/] },
        { title: "Adobe Flex Project", MIME: "application/vnd.adobe.fxp", extensions: [/\.fxp$/] },
        { title: "Adobe Portable Document Format", MIME: "application/pdf", extensions: [/\.pdf$/] },
        { title: "Adobe PostScript Printer Description File Format", MIME: "application/vnd.cups-ppd", extensions: [/\.ppd$/] },
        { title: "Adobe Shockwave Player", MIME: "application/x-director", extensions: [/\.dir$/] },
        { title: "Adobe XML Data Package", MIME: "application/vnd.adobe.xdp+xml", extensions: [/\.xdp$/] },
        { title: "Adobe XML Forms Data Format", MIME: "application/vnd.adobe.xfdf", extensions: [/\.xfdf$/] },
        { title: "Advanced Audio Coding (AAC)", MIME: "audio/x-aac", extensions: [/\.aac$/] },
        { title: "Ahead AIR Application", MIME: "application/vnd.ahead.space", extensions: [/\.ahead$/] },
        { title: "AirZip FileSECURE", MIME: "application/vnd.airzip.filesecure.azf", extensions: [/\.azf$/] },
        { title: "AirZip FileSECURE", MIME: "application/vnd.airzip.filesecure.azs", extensions: [/\.azs$/] },
        { title: "Amazon Kindle eBook format", MIME: "application/vnd.amazon.ebook", extensions: [/\.azw$/] },
        { title: "AmigaDE", MIME: "application/vnd.amiga.ami", extensions: [/\.ami$/] },
        { title: "Android Package Archive", MIME: "application/vnd.android.package-archive", extensions: [/\.apk$/] },
        { title: "ANSER-WEB Terminal Client - Certificate Issue", MIME: "application/vnd.anser-web-certificate-issue-initiation", extensions: [/\.cii$/] },
        { title: "ANSER-WEB Terminal Client - Web Funds Transfer", MIME: "application/vnd.anser-web-funds-transfer-initiation", extensions: [/\.fti$/] },
        { title: "Antix Game Player", MIME: "application/vnd.antix.game-component", extensions: [/\.atx$/] },
        { title: "Apple Installer Package", MIME: "application/vnd.apple.installer+xml", extensions: [/\.mpkg$/] },
        { title: "Applixware", MIME: "application/applixware", extensions: [/\.aw$/] },
        { title: "Archipelago Lesson Player", MIME: "application/vnd.hhe.lesson-player", extensions: [/\.les$/] },
        { title: "Arista Networks Software Image", MIME: "application/vnd.aristanetworks.swi", extensions: [/\.swi$/] },
        { title: "Assembler Source File", MIME: "text/x-asm", extensions: [/\.s$/] },
        { title: "Atom Publishing Protocol", MIME: "application/atomcat+xml", extensions: [/\.atomcat$/] },
        { title: "Atom Publishing Protocol Service Document", MIME: "application/atomsvc+xml", extensions: [/\.atomsvc$/] },
        { title: "Atom Syndication Format", MIME: "application/atom+xml", extensions: [/\.atom$/] },
        { title: "Attribute Certificate", MIME: "application/pkix-attr-cert", extensions: [/\.ac$/] },
        { title: "Audio Interchange File Format", MIME: "audio/x-aiff", extensions: [/\.aif$/] },
        { title: "Audio Video Interleave (AVI)", MIME: "video/x-msvideo", extensions: [/\.avi$/] },
        { title: "Audiograph", MIME: "application/vnd.audiograph", extensions: [/\.aep$/] },
        { title: "AutoCAD DXF", MIME: "image/vnd.dxf", extensions: [/\.dxf$/] },
        { title: "Autodesk Design Web Format (DWF)", MIME: "model/vnd.dwf", extensions: [/\.dwf$/] },
        { title: "BAS Partitur Format", MIME: "text/plain-bas", extensions: [/\.par$/] },
        { title: "Binary CPIO Archive", MIME: "application/x-bcpio", extensions: [/\.bcpio$/] },
        { title: "Binary Data", MIME: "application/octet-stream", extensions: [/\.bin$/] },
        { title: "Bitmap Image File", MIME: "image/bmp", extensions: [/\.bmp$/] },
        { title: "BitTorrent", MIME: "application/x-bittorrent", extensions: [/\.torrent$/] },
        { title: "Blackberry COD File", MIME: "application/vnd.rim.cod", extensions: [/\.cod$/] },
        { title: "Blueice Research Multipass", MIME: "application/vnd.blueice.multipass", extensions: [/\.mpm$/] },
        { title: "BMI Drawing Data Interchange", MIME: "application/vnd.bmi", extensions: [/\.bmi$/] },
        { title: "Bourne Shell Script", MIME: "application/x-sh", extensions: [/\.sh$/] },
        { title: "BTIF", MIME: "image/prs.btif", extensions: [/\.btif$/] },
        { title: "BusinessObjects", MIME: "application/vnd.businessobjects", extensions: [/\.rep$/] },
        { title: "Bzip Archive", MIME: "application/x-bzip", extensions: [/\.bz$/] },
        { title: "Bzip2 Archive", MIME: "application/x-bzip2", extensions: [/\.bz2$/] },
        { title: "C Shell Script", MIME: "application/x-csh", extensions: [/\.csh$/] },
        { title: "C Source File", MIME: "text/x-c", extensions: [/\.c$/] },
        { title: "CambridgeSoft Chem Draw", MIME: "application/vnd.chemdraw+xml", extensions: [/\.cdxml$/] },
        { title: "Cascading Style Sheets (CSS)", MIME: "text/css", extensions: [/\.css$/] },
        { title: "ChemDraw eXchange file", MIME: "chemical/x-cdx", extensions: [/\.cdx$/] },
        { title: "Chemical Markup Language", MIME: "chemical/x-cml", extensions: [/\.cml$/] },
        { title: "Chemical Style Markup Language", MIME: "chemical/x-csml", extensions: [/\.csml$/] },
        { title: "CIM Database", MIME: "application/vnd.contact.cmsg", extensions: [/\.cdbcmsg$/] },
        { title: "Claymore Data Files", MIME: "application/vnd.claymore", extensions: [/\.cla$/] },
        { title: "Clonk Game", MIME: "application/vnd.clonk.c4group", extensions: [/\.c4g$/] },
        { title: "Close Captioning - Subtitle", MIME: "image/vnd.dvb.subtitle", extensions: [/\.sub$/] },
        { title: "Cloud Data Management Interface (CDMI) - Capability", MIME: "application/cdmi-capability", extensions: [/\.cdmia$/] },
        { title: "Cloud Data Management Interface (CDMI) - Contaimer", MIME: "application/cdmi-container", extensions: [/\.cdmic$/] },
        { title: "Cloud Data Management Interface (CDMI) - Domain", MIME: "application/cdmi-domain", extensions: [/\.cdmid$/] },
        { title: "Cloud Data Management Interface (CDMI) - Object", MIME: "application/cdmi-object", extensions: [/\.cdmio$/] },
        { title: "Cloud Data Management Interface (CDMI) - Queue", MIME: "application/cdmi-queue", extensions: [/\.cdmiq$/] },
        { title: "ClueTrust CartoMobile - Config", MIME: "application/vnd.cluetrust.cartomobile-config", extensions: [/\.c11amc$/] },
        { title: "ClueTrust CartoMobile - Config Package", MIME: "application/vnd.cluetrust.cartomobile-config-pkg", extensions: [/\.c11amz$/] },
        { title: "CMU Image", MIME: "image/x-cmu-raster", extensions: [/\.ras$/] },
        { title: "COLLADA", MIME: "model/vnd.collada+xml", extensions: [/\.dae$/] },
        { title: "Comma-Seperated Values", MIME: "text/csv", extensions: [/\.csv$/] },
        { title: "Compact Pro", MIME: "application/mac-compactpro", extensions: [/\.cpt$/] },
        { title: "Compiled Wireless Markup Language (WMLC)", MIME: "application/vnd.wap.wmlc", extensions: [/\.wmlc$/] },
        { title: "Computer Graphics Metafile", MIME: "image/cgm", extensions: [/\.cgm$/] },
        { title: "CoolTalk", MIME: "x-conference/x-cooltalk", extensions: [/\.ice$/] },
        { title: "Corel Metafile Exchange (CMX)", MIME: "image/x-cmx", extensions: [/\.cmx$/] },
        { title: "CorelXARA", MIME: "application/vnd.xara", extensions: [/\.xar$/] },
        { title: "CosmoCaller", MIME: "application/vnd.cosmocaller", extensions: [/\.cmc$/] },
        { title: "CPIO Archive", MIME: "application/x-cpio", extensions: [/\.cpio$/] },
        { title: "CrickSoftware - Clicker", MIME: "application/vnd.crick.clicker", extensions: [/\.clkx$/] },
        { title: "CrickSoftware - Clicker - Keyboard", MIME: "application/vnd.crick.clicker.keyboard", extensions: [/\.clkk$/] },
        { title: "CrickSoftware - Clicker - Palette", MIME: "application/vnd.crick.clicker.palette", extensions: [/\.clkp$/] },
        { title: "CrickSoftware - Clicker - Template", MIME: "application/vnd.crick.clicker.template", extensions: [/\.clkt$/] },
        { title: "CrickSoftware - Clicker - Wordbank", MIME: "application/vnd.crick.clicker.wordbank", extensions: [/\.clkw$/] },
        { title: "Critical Tools - PERT Chart EXPERT", MIME: "application/vnd.criticaltools.wbs+xml", extensions: [/\.wbs$/] },
        { title: "CryptoNote", MIME: "application/vnd.rig.cryptonote", extensions: [/\.cryptonote$/] },
        { title: "Crystallographic Interchange Format", MIME: "chemical/x-cif", extensions: [/\.cif$/] },
        { title: "CrystalMaker Data Format", MIME: "chemical/x-cmdf", extensions: [/\.cmdf$/] },
        { title: "CU-SeeMe", MIME: "application/cu-seeme", extensions: [/\.cu$/] },
        { title: "CU-Writer", MIME: "application/prs.cww", extensions: [/\.cww$/] },
        { title: "Curl - Applet", MIME: "text/vnd.curl", extensions: [/\.curl$/] },
        { title: "Curl - Detached Applet", MIME: "text/vnd.curl.dcurl", extensions: [/\.dcurl$/] },
        { title: "Curl - Manifest File", MIME: "text/vnd.curl.mcurl", extensions: [/\.mcurl$/] },
        { title: "Curl - Source Code", MIME: "text/vnd.curl.scurl", extensions: [/\.scurl$/] },
        { title: "CURL Applet", MIME: "application/vnd.curl.car", extensions: [/\.car$/] },
        { title: "CURL Applet", MIME: "application/vnd.curl.pcurl", extensions: [/\.pcurl$/] },
        { title: "CustomMenu", MIME: "application/vnd.yellowriver-custom-menu", extensions: [/\.cmp$/] },
        { title: "Data Structure for the Security Suitability of Cryptographic Algorithms", MIME: "application/dssc+der", extensions: [/\.dssc$/] },
        { title: "Data Structure for the Security Suitability of Cryptographic Algorithms", MIME: "application/dssc+xml", extensions: [/\.xdssc$/] },
        { title: "Debian Package", MIME: "application/x-debian-package", extensions: [/\.deb$/] },
        { title: "DECE Audio", MIME: "audio/vnd.dece.audio", extensions: [/\.uva$/] },
        { title: "DECE Graphic", MIME: "image/vnd.dece.graphic", extensions: [/\.uvi$/] },
        { title: "DECE High Definition Video", MIME: "video/vnd.dece.hd", extensions: [/\.uvh$/] },
        { title: "DECE Mobile Video", MIME: "video/vnd.dece.mobile", extensions: [/\.uvm$/] },
        { title: "DECE MP4", MIME: "video/vnd.uvvu.mp4", extensions: [/\.uvu$/] },
        { title: "DECE PD Video", MIME: "video/vnd.dece.pd", extensions: [/\.uvp$/] },
        { title: "DECE SD Video", MIME: "video/vnd.dece.sd", extensions: [/\.uvs$/] },
        { title: "DECE Video", MIME: "video/vnd.dece.video", extensions: [/\.uvv$/] },
        { title: "Device Independent File Format (DVI)", MIME: "application/x-dvi", extensions: [/\.dvi$/] },
        { title: "Digital Siesmograph Networks - SEED Datafiles", MIME: "application/vnd.fdsn.seed", extensions: [/\.seed$/] },
        { title: "Digital Talking Book", MIME: "application/x-dtbook+xml", extensions: [/\.dtb$/] },
        { title: "Digital Talking Book - Resource File", MIME: "application/x-dtbresource+xml", extensions: [/\.res$/] },
        { title: "Digital Video Broadcasting", MIME: "application/vnd.dvb.ait", extensions: [/\.ait$/] },
        { title: "Digital Video Broadcasting", MIME: "application/vnd.dvb.service", extensions: [/\.svc$/] },
        { title: "Digital Winds Music", MIME: "audio/vnd.digital-winds", extensions: [/\.eol$/] },
        { title: "DjVu", MIME: "image/vnd.djvu", extensions: [/\.djvu$/] },
        { title: "Document Type Definition", MIME: "application/xml-dtd", extensions: [/\.dtd$/] },
        { title: "Dolby Meridian Lossless Packing", MIME: "application/vnd.dolby.mlp", extensions: [/\.mlp$/] },
        { title: "Doom Video Game", MIME: "application/x-doom", extensions: [/\.wad$/] },
        { title: "DPGraph", MIME: "application/vnd.dpgraph", extensions: [/\.dpg$/] },
        { title: "DRA Audio", MIME: "audio/vnd.dra", extensions: [/\.dra$/] },
        { title: "DreamFactory", MIME: "application/vnd.dreamfactory", extensions: [/\.dfac$/] },
        { title: "DTS Audio", MIME: "audio/vnd.dts", extensions: [/\.dts$/] },
        { title: "DTS High Definition Audio", MIME: "audio/vnd.dts.hd", extensions: [/\.dtshd$/] },
        { title: "DWG Drawing", MIME: "image/vnd.dwg", extensions: [/\.dwg$/] },
        { title: "DynaGeo", MIME: "application/vnd.dynageo", extensions: [/\.geo$/] },
        { title: "ECMAScript", MIME: "application/ecmascript", extensions: [/\.es$/] },
        { title: "EcoWin Chart", MIME: "application/vnd.ecowin.chart", extensions: [/\.mag$/] },
        { title: "EDMICS 2000", MIME: "image/vnd.fujixerox.edmics-mmr", extensions: [/\.mmr$/] },
        { title: "EDMICS 2000", MIME: "image/vnd.fujixerox.edmics-rlc", extensions: [/\.rlc$/] },
        { title: "Efficient XML Interchange", MIME: "application/exi", extensions: [/\.exi$/] },
        { title: "EFI Proteus", MIME: "application/vnd.proteus.magazine", extensions: [/\.mgz$/] },
        { title: "Electronic Publication", MIME: "application/epub+zip", extensions: [/\.epub$/] },
        { title: "Email Message", MIME: "message/rfc822", extensions: [/\.eml$/] },
        { title: "Enliven Viewer", MIME: "application/vnd.enliven", extensions: [/\.nml$/] },
        { title: "Express by Infoseek", MIME: "application/vnd.is-xpr", extensions: [/\.xpr$/] },
        { title: "eXtended Image File Format (XIFF)", MIME: "image/vnd.xiff", extensions: [/\.xif$/] },
        { title: "Extensible Forms Description Language", MIME: "application/vnd.xfdl", extensions: [/\.xfdl$/] },
        { title: "Extensible MultiModal Annotation", MIME: "application/emma+xml", extensions: [/\.emma$/] },
        { title: "EZPix Secure Photo Album", MIME: "application/vnd.ezpix-album", extensions: [/\.ez2$/] },
        { title: "EZPix Secure Photo Album", MIME: "application/vnd.ezpix-package", extensions: [/\.ez3$/] },
        { title: "FAST Search & Transfer ASA", MIME: "image/vnd.fst", extensions: [/\.fst$/] },
        { title: "FAST Search & Transfer ASA", MIME: "video/vnd.fvt", extensions: [/\.fvt$/] },
        { title: "FastBid Sheet", MIME: "image/vnd.fastbidsheet", extensions: [/\.fbs$/] },
        { title: "FCS Express Layout Link", MIME: "application/vnd.denovo.fcselayout-link", extensions: [/\.fe_launch$/] },
        { title: "Flash Video", MIME: "video/x-f4v", extensions: [/\.f4v$/] },
        { title: "Flash Video", MIME: "video/x-flv", extensions: [/\.flv$/] },
        { title: "FlashPix", MIME: "image/vnd.fpx", extensions: [/\.fpx$/] },
        { title: "FlashPix", MIME: "image/vnd.net-fpx", extensions: [/\.npx$/] },
        { title: "FLEXSTOR", MIME: "text/vnd.fmi.flexstor", extensions: [/\.flx$/] },
        { title: "FLI/FLC Animation Format", MIME: "video/x-fli", extensions: [/\.fli$/] },
        { title: "FluxTime Clip", MIME: "application/vnd.fluxtime.clip", extensions: [/\.ftc$/] },
        { title: "Forms Data Format", MIME: "application/vnd.fdf", extensions: [/\.fdf$/] },
        { title: "Fortran Source File", MIME: "text/x-fortran", extensions: [/\.f$/] },
        { title: "FrameMaker Interchange Format", MIME: "application/vnd.mif", extensions: [/\.mif$/] },
        { title: "FrameMaker Normal Format", MIME: "application/vnd.framemaker", extensions: [/\.fm$/] },
        { title: "FreeHand MX", MIME: "image/x-freehand", extensions: [/\.fh$/] },
        { title: "Friendly Software Corporation", MIME: "application/vnd.fsc.weblaunch", extensions: [/\.fsc$/] },
        { title: "Frogans Player", MIME: "application/vnd.frogans.fnc", extensions: [/\.fnc$/] },
        { title: "Frogans Player", MIME: "application/vnd.frogans.ltf", extensions: [/\.ltf$/] },
        { title: "Fujitsu - Xerox 2D CAD Data", MIME: "application/vnd.fujixerox.ddd", extensions: [/\.ddd$/] },
        { title: "Fujitsu - Xerox DocuWorks", MIME: "application/vnd.fujixerox.docuworks", extensions: [/\.xdw$/] },
        { title: "Fujitsu - Xerox DocuWorks Binder", MIME: "application/vnd.fujixerox.docuworks.binder", extensions: [/\.xbd$/] },
        { title: "Fujitsu Oasys", MIME: "application/vnd.fujitsu.oasys", extensions: [/\.oas$/] },
        { title: "Fujitsu Oasys", MIME: "application/vnd.fujitsu.oasys2", extensions: [/\.oa2$/] },
        { title: "Fujitsu Oasys", MIME: "application/vnd.fujitsu.oasys3", extensions: [/\.oa3$/] },
        { title: "Fujitsu Oasys", MIME: "application/vnd.fujitsu.oasysgp", extensions: [/\.fg5$/] },
        { title: "Fujitsu Oasys", MIME: "application/vnd.fujitsu.oasysprs", extensions: [/\.bh2$/] },
        { title: "FutureSplash Animator", MIME: "application/x-futuresplash", extensions: [/\.spl$/] },
        { title: "FuzzySheet", MIME: "application/vnd.fuzzysheet", extensions: [/\.fzs$/] },
        { title: "G3 Fax Image", MIME: "image/g3fax", extensions: [/\.g3$/] },
        { title: "GameMaker ActiveX", MIME: "application/vnd.gmx", extensions: [/\.gmx$/] },
        { title: "Gen-Trix Studio", MIME: "model/vnd.gtw", extensions: [/\.gtw$/] },
        { title: "Genomatix Tuxedo Framework", MIME: "application/vnd.genomatix.tuxedo", extensions: [/\.txd$/] },
        { title: "GeoGebra", MIME: "application/vnd.geogebra.file", extensions: [/\.ggb$/] },
        { title: "GeoGebra", MIME: "application/vnd.geogebra.tool", extensions: [/\.ggt$/] },
        { title: "Geometric Description Language (GDL)", MIME: "model/vnd.gdl", extensions: [/\.gdl$/] },
        { title: "GeoMetry Explorer", MIME: "application/vnd.geometry-explorer", extensions: [/\.gex$/] },
        { title: "GEONExT and JSXGraph", MIME: "application/vnd.geonext", extensions: [/\.gxt$/] },
        { title: "GeoplanW", MIME: "application/vnd.geoplan", extensions: [/\.g2w$/] },
        { title: "GeospacW", MIME: "application/vnd.geospace", extensions: [/\.g3w$/] },
        { title: "Ghostscript Font", MIME: "application/x-font-ghostscript", extensions: [/\.gsf$/] },
        { title: "Glyph Bitmap Distribution Format", MIME: "application/x-font-bdf", extensions: [/\.bdf$/] },
        { title: "GNU Tar Files", MIME: "application/x-gtar", extensions: [/\.gtar$/] },
        { title: "GNU Texinfo Document", MIME: "application/x-texinfo", extensions: [/\.texinfo$/] },
        { title: "Gnumeric", MIME: "application/x-gnumeric", extensions: [/\.gnumeric$/] },
        { title: "Google Earth - KML", MIME: "application/vnd.google-earth.kml+xml", extensions: [/\.kml$/] },
        { title: "Google Earth - Zipped KML", MIME: "application/vnd.google-earth.kmz", extensions: [/\.kmz$/] },
        { title: "GrafEq", MIME: "application/vnd.grafeq", extensions: [/\.gqf$/] },
        { title: "Graphics Interchange Format", MIME: "image/gif", extensions: [/\.gif$/] },
        { title: "Graphviz", MIME: "text/vnd.graphviz", extensions: [/\.gv$/] },
        { title: "Groove - Account", MIME: "application/vnd.groove-account", extensions: [/\.gac$/] },
        { title: "Groove - Help", MIME: "application/vnd.groove-help", extensions: [/\.ghf$/] },
        { title: "Groove - Identity Message", MIME: "application/vnd.groove-identity-message", extensions: [/\.gim$/] },
        { title: "Groove - Injector", MIME: "application/vnd.groove-injector", extensions: [/\.grv$/] },
        { title: "Groove - Tool Message", MIME: "application/vnd.groove-tool-message", extensions: [/\.gtm$/] },
        { title: "Groove - Tool Template", MIME: "application/vnd.groove-tool-template", extensions: [/\.tpl$/] },
        { title: "Groove - Vcard", MIME: "application/vnd.groove-vcard", extensions: [/\.vcg$/] },
        { title: "H.261", MIME: "video/h261", extensions: [/\.h261$/] },
        { title: "H.263", MIME: "video/h263", extensions: [/\.h263$/] },
        { title: "H.264", MIME: "video/h264", extensions: [/\.h264$/] },
        { title: "Hewlett Packard Instant Delivery", MIME: "application/vnd.hp-hpid", extensions: [/\.hpid$/] },
        { title: "Hewlett-Packard's WebPrintSmart", MIME: "application/vnd.hp-hps", extensions: [/\.hps$/] },
        { title: "Hierarchical Data Format", MIME: "application/x-hdf", extensions: [/\.hdf$/] },
        { title: "Hit'n'Mix", MIME: "audio/vnd.rip", extensions: [/\.rip$/] },
        { title: "Homebanking Computer Interface (HBCI)", MIME: "application/vnd.hbci", extensions: [/\.hbci$/] },
        { title: "HP Indigo Digital Press - Job Layout Languate", MIME: "application/vnd.hp-jlyt", extensions: [/\.jlt$/] },
        { title: "HP Printer Command Language", MIME: "application/vnd.hp-pcl", extensions: [/\.pcl$/] },
        { title: "HP-GL/2 and HP RTL", MIME: "application/vnd.hp-hpgl", extensions: [/\.hpgl$/] },
        { title: "HV Script", MIME: "application/vnd.yamaha.hv-script", extensions: [/\.hvs$/] },
        { title: "HV Voice Dictionary", MIME: "application/vnd.yamaha.hv-dic", extensions: [/\.hvd$/] },
        { title: "HV Voice Parameter", MIME: "application/vnd.yamaha.hv-voice", extensions: [/\.hvp$/] },
        { title: "Hydrostatix Master Suite", MIME: "application/vnd.hydrostatix.sof-data", extensions: [/\.sfd-hdstx$/] },
        { title: "Hyperstudio", MIME: "application/hyperstudio", extensions: [/\.stk$/] },
        { title: "Hypertext Application Language", MIME: "application/vnd.hal+xml", extensions: [/\.hal$/] },
        { title: "HyperText Markup Language (HTML)", MIME: "text/html", extensions: [/\.html$/] },
        { title: "IBM DB2 Rights Manager", MIME: "application/vnd.ibm.rights-management", extensions: [/\.irm$/] },
        { title: "IBM Electronic Media Management System - Secure Container", MIME: "application/vnd.ibm.secure-container", extensions: [/\.sc$/] },
        { title: "iCalendar", MIME: "text/calendar", extensions: [/\.ics$/] },
        { title: "ICC profile", MIME: "application/vnd.iccprofile", extensions: [/\.icc$/] },
        { title: "Icon Image", MIME: "image/x-icon", extensions: [/\.ico$/] },
        { title: "igLoader", MIME: "application/vnd.igloader", extensions: [/\.igl$/] },
        { title: "Image Exchange Format", MIME: "image/ief", extensions: [/\.ief$/] },
        { title: "ImmerVision PURE Players", MIME: "application/vnd.immervision-ivp", extensions: [/\.ivp$/] },
        { title: "ImmerVision PURE Players", MIME: "application/vnd.immervision-ivu", extensions: [/\.ivu$/] },
        { title: "IMS Networks", MIME: "application/reginfo+xml", extensions: [/\.rif$/] },
        { title: "In3D - 3DML", MIME: "text/vnd.in3d.3dml", extensions: [/\.3dml$/] },
        { title: "In3D - 3DML", MIME: "text/vnd.in3d.spot", extensions: [/\.spot$/] },
        { title: "Initial Graphics Exchange Specification (IGES)", MIME: "model/iges", extensions: [/\.igs$/] },
        { title: "Interactive Geometry Software", MIME: "application/vnd.intergeo", extensions: [/\.i2g$/] },
        { title: "Interactive Geometry Software Cinderella", MIME: "application/vnd.cinderella", extensions: [/\.cdy$/] },
        { title: "Intercon FormNet", MIME: "application/vnd.intercon.formnet", extensions: [/\.xpw$/] },
        { title: "International Society for Advancement of Cytometry", MIME: "application/vnd.isac.fcs", extensions: [/\.fcs$/] },
        { title: "Internet Protocol Flow Information Export", MIME: "application/ipfix", extensions: [/\.ipfix$/] },
        { title: "Internet Public Key Infrastructure - Certificate", MIME: "application/pkix-cert", extensions: [/\.cer$/] },
        { title: "Internet Public Key Infrastructure - Certificate Management Protocole", MIME: "application/pkixcmp", extensions: [/\.pki$/] },
        { title: "Internet Public Key Infrastructure - Certificate Revocation Lists", MIME: "application/pkix-crl", extensions: [/\.crl$/] },
        { title: "Internet Public Key Infrastructure - Certification Path", MIME: "application/pkix-pkipath", extensions: [/\.pkipath$/] },
        { title: "IOCOM Visimeet", MIME: "application/vnd.insors.igm", extensions: [/\.igm$/] },
        { title: "IP Unplugged Roaming Client", MIME: "application/vnd.ipunplugged.rcprofile", extensions: [/\.rcprofile$/] },
        { title: "iRepository / Lucidoc Editor", MIME: "application/vnd.irepository.package+xml", extensions: [/\.irp$/] },
        { title: "J2ME App Descriptor", MIME: "text/vnd.sun.j2me.app-descriptor", extensions: [/\.jad$/] },
        { title: "Java Archive", MIME: "application/java-archive", extensions: [/\.jar$/] },
        { title: "Java Bytecode File", MIME: "application/java-vm", extensions: [/\.class$/] },
        { title: "Java Network Launching Protocol", MIME: "application/x-java-jnlp-file", extensions: [/\.jnlp$/] },
        { title: "Java Serialized Object", MIME: "application/java-serialized-object", extensions: [/\.ser$/] },
        { title: "Java Source File", MIME: "text/x-java-source,java", extensions: [/\.java$/] },
        { title: "JavaScript", MIME: "application/javascript", extensions: [/\.js$/] },
        { title: "JavaScript Object Notation (JSON)", MIME: "application/json", extensions: [/\.json$/] },
        { title: "Joda Archive", MIME: "application/vnd.joost.joda-archive", extensions: [/\.joda$/] },
        { title: "JPEG 2000 Compound Image File Format", MIME: "video/jpm", extensions: [/\.jpm$/] },
        { title: "JPEG Image", MIME: "image/jpeg", extensions: [/\.jpeg$/, /\.jpg$/] },
        { title: "JPGVideo", MIME: "video/jpeg", extensions: [/\.jpgv$/] },
        { title: "Kahootz", MIME: "application/vnd.kahootz", extensions: [/\.ktz$/] },
        { title: "Karaoke on Chipnuts Chipsets", MIME: "application/vnd.chipnuts.karaoke-mmd", extensions: [/\.mmd$/] },
        { title: "KDE KOffice Office Suite - Karbon", MIME: "application/vnd.kde.karbon", extensions: [/\.karbon$/] },
        { title: "KDE KOffice Office Suite - KChart", MIME: "application/vnd.kde.kchart", extensions: [/\.chrt$/] },
        { title: "KDE KOffice Office Suite - Kformula", MIME: "application/vnd.kde.kformula", extensions: [/\.kfo$/] },
        { title: "KDE KOffice Office Suite - Kivio", MIME: "application/vnd.kde.kivio", extensions: [/\.flw$/] },
        { title: "KDE KOffice Office Suite - Kontour", MIME: "application/vnd.kde.kontour", extensions: [/\.kon$/] },
        { title: "KDE KOffice Office Suite - Kpresenter", MIME: "application/vnd.kde.kpresenter", extensions: [/\.kpr$/] },
        { title: "KDE KOffice Office Suite - Kspread", MIME: "application/vnd.kde.kspread", extensions: [/\.ksp$/] },
        { title: "KDE KOffice Office Suite - Kword", MIME: "application/vnd.kde.kword", extensions: [/\.kwd$/] },
        { title: "Kenamea App", MIME: "application/vnd.kenameaapp", extensions: [/\.htke$/] },
        { title: "Kidspiration", MIME: "application/vnd.kidspiration", extensions: [/\.kia$/] },
        { title: "Kinar Applications", MIME: "application/vnd.kinar", extensions: [/\.kne$/] },
        { title: "Kodak Storyshare", MIME: "application/vnd.kodak-descriptor", extensions: [/\.sse$/] },
        { title: "Laser App Enterprise", MIME: "application/vnd.las.las+xml", extensions: [/\.lasxml$/] },
        { title: "LaTeX", MIME: "application/x-latex", extensions: [/\.latex$/] },
        { title: "Life Balance - Desktop Edition", MIME: "application/vnd.llamagraphics.life-balance.desktop", extensions: [/\.lbd$/] },
        { title: "Life Balance - Exchange Format", MIME: "application/vnd.llamagraphics.life-balance.exchange+xml", extensions: [/\.lbe$/] },
        { title: "Lightspeed Audio Lab", MIME: "application/vnd.jam", extensions: [/\.jam$/] },
        { title: "Lotus 1-2-3", MIME: "application/vnd.lotus-1-2-3", extensions: [/\0.123$/] },
        { title: "Lotus Approach", MIME: "application/vnd.lotus-approach", extensions: [/\.apr$/] },
        { title: "Lotus Freelance", MIME: "application/vnd.lotus-freelance", extensions: [/\.pre$/] },
        { title: "Lotus Notes", MIME: "application/vnd.lotus-notes", extensions: [/\.nsf$/] },
        { title: "Lotus Organizer", MIME: "application/vnd.lotus-organizer", extensions: [/\.org$/] },
        { title: "Lotus Screencam", MIME: "application/vnd.lotus-screencam", extensions: [/\.scm$/] },
        { title: "Lotus Wordpro", MIME: "application/vnd.lotus-wordpro", extensions: [/\.lwp$/] },
        { title: "Lucent Voice", MIME: "audio/vnd.lucent.voice", extensions: [/\.lvp$/] },
        { title: "M3U (Multimedia Playlist)", MIME: "audio/x-mpegurl", extensions: [/\.m3u$/] },
        { title: "M4v", MIME: "video/x-m4v", extensions: [/\.m4v$/] },
        { title: "Macintosh BinHex 4.0", MIME: "application/mac-binhex40", extensions: [/\.hqx$/] },
        { title: "MacPorts Port System", MIME: "application/vnd.macports.portpkg", extensions: [/\.portpkg$/] },
        { title: "MapGuide DBXML", MIME: "application/vnd.osgeo.mapguide.package", extensions: [/\.mgp$/] },
        { title: "MARC Formats", MIME: "application/marc", extensions: [/\.mrc$/] },
        { title: "MARC21 XML Schema", MIME: "application/marcxml+xml", extensions: [/\.mrcx$/] },
        { title: "Material Exchange Format", MIME: "application/mxf", extensions: [/\.mxf$/] },
        { title: "Mathematica Notebook Player", MIME: "application/vnd.wolfram.player", extensions: [/\.nbp$/] },
        { title: "Mathematica Notebooks", MIME: "application/mathematica", extensions: [/\.ma$/] },
        { title: "Mathematical Markup Language", MIME: "application/mathml+xml", extensions: [/\.mathml$/] },
        { title: "Mbox database files", MIME: "application/mbox", extensions: [/\.mbox$/] },
        { title: "MedCalc", MIME: "application/vnd.medcalcdata", extensions: [/\.mc1$/] },
        { title: "Media Server Control Markup Language", MIME: "application/mediaservercontrol+xml", extensions: [/\.mscml$/] },
        { title: "MediaRemote", MIME: "application/vnd.mediastation.cdkey", extensions: [/\.cdkey$/] },
        { title: "Medical Waveform Encoding Format", MIME: "application/vnd.mfer", extensions: [/\.mwf$/] },
        { title: "Melody Format for Mobile Platform", MIME: "application/vnd.mfmp", extensions: [/\.mfm$/] },
        { title: "Mesh Data Type", MIME: "model/mesh", extensions: [/\.msh$/] },
        { title: "Metadata Authority Description Schema", MIME: "application/mads+xml", extensions: [/\.mads$/] },
        { title: "Metadata Encoding and Transmission Standard", MIME: "application/mets+xml", extensions: [/\.mets$/] },
        { title: "Metadata Object Description Schema", MIME: "application/mods+xml", extensions: [/\.mods$/] },
        { title: "Metalink", MIME: "application/metalink4+xml", extensions: [/\.meta4$/] },
        { title: "Micosoft PowerPoint - Macro-Enabled Template File", MIME: "application/vnd.ms-powerpoint.template.macroenabled.12", extensions: [/\.potm$/] },
        { title: "Micosoft Word - Macro-Enabled Document", MIME: "application/vnd.ms-word.document.macroenabled.12", extensions: [/\.docm$/] },
        { title: "Micosoft Word - Macro-Enabled Template", MIME: "application/vnd.ms-word.template.macroenabled.12", extensions: [/\.dotm$/] },
        { title: "Micro CADAM Helix D&D", MIME: "application/vnd.mcd", extensions: [/\.mcd$/] },
        { title: "Micrografx", MIME: "application/vnd.micrografx.flo", extensions: [/\.flo$/] },
        { title: "Micrografx iGrafx Professional", MIME: "application/vnd.micrografx.igx", extensions: [/\.igx$/] },
        { title: "MICROSEC e-Szign¢", MIME: "application/vnd.eszigno3+xml", extensions: [/\.es3$/] },
        { title: "Microsoft Access", MIME: "application/x-msaccess", extensions: [/\.mdb$/] },
        { title: "Microsoft Advanced Systems Format (ASF)", MIME: "video/x-ms-asf", extensions: [/\.asf$/] },
        { title: "Microsoft Application", MIME: "application/x-msdownload", extensions: [/\.exe$/] },
        { title: "Microsoft Artgalry", MIME: "application/vnd.ms-artgalry", extensions: [/\.cil$/] },
        { title: "Microsoft Cabinet File", MIME: "application/vnd.ms-cab-compressed", extensions: [/\.cab$/] },
        { title: "Microsoft Class Server", MIME: "application/vnd.ms-ims", extensions: [/\.ims$/] },
        { title: "Microsoft ClickOnce", MIME: "application/x-ms-application", extensions: [/\.application$/] },
        { title: "Microsoft Clipboard Clip", MIME: "application/x-msclip", extensions: [/\.clp$/] },
        { title: "Microsoft Document Imaging Format", MIME: "image/vnd.ms-modi", extensions: [/\.mdi$/] },
        { title: "Microsoft Embedded OpenType", MIME: "application/vnd.ms-fontobject", extensions: [/\.eot$/] },
        { title: "Microsoft Excel", MIME: "application/vnd.ms-excel", extensions: [/\.xls$/] },
        { title: "Microsoft Excel - Add-In File", MIME: "application/vnd.ms-excel.addin.macroenabled.12", extensions: [/\.xlam$/] },
        { title: "Microsoft Excel - Binary Workbook", MIME: "application/vnd.ms-excel.sheet.binary.macroenabled.12", extensions: [/\.xlsb$/] },
        { title: "Microsoft Excel - Macro-Enabled Template File", MIME: "application/vnd.ms-excel.template.macroenabled.12", extensions: [/\.xltm$/] },
        { title: "Microsoft Excel - Macro-Enabled Workbook", MIME: "application/vnd.ms-excel.sheet.macroenabled.12", extensions: [/\.xlsm$/] },
        { title: "Microsoft Html Help File", MIME: "application/vnd.ms-htmlhelp", extensions: [/\.chm$/] },
        { title: "Microsoft Information Card", MIME: "application/x-mscardfile", extensions: [/\.crd$/] },
        { title: "Microsoft Learning Resource Module", MIME: "application/vnd.ms-lrm", extensions: [/\.lrm$/] },
        { title: "Microsoft MediaView", MIME: "application/x-msmediaview", extensions: [/\.mvb$/] },
        { title: "Microsoft Money", MIME: "application/x-msmoney", extensions: [/\.mny$/] },
        { title: "Microsoft Office - OOXML - Presentation", MIME: "application/vnd.openxmlformats-officedocument.presentationml.presentation", extensions: [/\.pptx$/] },
        { title: "Microsoft Office - OOXML - Presentation (Slide)", MIME: "application/vnd.openxmlformats-officedocument.presentationml.slide", extensions: [/\.sldx$/] },
        { title: "Microsoft Office - OOXML - Presentation (Slideshow)", MIME: "application/vnd.openxmlformats-officedocument.presentationml.slideshow", extensions: [/\.ppsx$/] },
        { title: "Microsoft Office - OOXML - Presentation Template", MIME: "application/vnd.openxmlformats-officedocument.presentationml.template", extensions: [/\.potx$/] },
        { title: "Microsoft Office - OOXML - Spreadsheet", MIME: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", extensions: [/\.xlsx$/] },
        { title: "Microsoft Office - OOXML - Spreadsheet Teplate", MIME: "application/vnd.openxmlformats-officedocument.spreadsheetml.template", extensions: [/\.xltx$/] },
        { title: "Microsoft Office - OOXML - Word Document", MIME: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", extensions: [/\.docx$/] },
        { title: "Microsoft Office - OOXML - Word Document Template", MIME: "application/vnd.openxmlformats-officedocument.wordprocessingml.template", extensions: [/\.dotx$/] },
        { title: "Microsoft Office Binder", MIME: "application/x-msbinder", extensions: [/\.obd$/] },
        { title: "Microsoft Office System Release Theme", MIME: "application/vnd.ms-officetheme", extensions: [/\.thmx$/] },
        { title: "Microsoft OneNote", MIME: "application/onenote", extensions: [/\.onetoc$/] },
        { title: "Microsoft PlayReady Ecosystem", MIME: "audio/vnd.ms-playready.media.pya", extensions: [/\.pya$/] },
        { title: "Microsoft PlayReady Ecosystem Video", MIME: "video/vnd.ms-playready.media.pyv", extensions: [/\.pyv$/] },
        { title: "Microsoft PowerPoint", MIME: "application/vnd.ms-powerpoint", extensions: [/\.ppt$/] },
        { title: "Microsoft PowerPoint - Add-in file", MIME: "application/vnd.ms-powerpoint.addin.macroenabled.12", extensions: [/\.ppam$/] },
        { title: "Microsoft PowerPoint - Macro-Enabled Open XML Slide", MIME: "application/vnd.ms-powerpoint.slide.macroenabled.12", extensions: [/\.sldm$/] },
        { title: "Microsoft PowerPoint - Macro-Enabled Presentation File", MIME: "application/vnd.ms-powerpoint.presentation.macroenabled.12", extensions: [/\.pptm$/] },
        { title: "Microsoft PowerPoint - Macro-Enabled Slide Show File", MIME: "application/vnd.ms-powerpoint.slideshow.macroenabled.12", extensions: [/\.ppsm$/] },
        { title: "Microsoft Project", MIME: "application/vnd.ms-project", extensions: [/\.mpp$/] },
        { title: "Microsoft Publisher", MIME: "application/x-mspublisher", extensions: [/\.pub$/] },
        { title: "Microsoft Schedule+", MIME: "application/x-msschedule", extensions: [/\.scd$/] },
        { title: "Microsoft Silverlight", MIME: "application/x-silverlight-app", extensions: [/\.xap$/] },
        { title: "Microsoft Trust UI Provider - Certificate Trust Link", MIME: "application/vnd.ms-pki.stl", extensions: [/\.stl$/] },
        { title: "Microsoft Trust UI Provider - Security Catalog", MIME: "application/vnd.ms-pki.seccat", extensions: [/\.cat$/] },
        { title: "Microsoft Visio", MIME: "application/vnd.visio", extensions: [/\.vsd$/] },
        { title: "Microsoft Windows Media", MIME: "video/x-ms-wm", extensions: [/\.wm$/] },
        { title: "Microsoft Windows Media Audio", MIME: "audio/x-ms-wma", extensions: [/\.wma$/] },
        { title: "Microsoft Windows Media Audio Redirector", MIME: "audio/x-ms-wax", extensions: [/\.wax$/] },
        { title: "Microsoft Windows Media Audio/Video Playlist", MIME: "video/x-ms-wmx", extensions: [/\.wmx$/] },
        { title: "Microsoft Windows Media Player Download Package", MIME: "application/x-ms-wmd", extensions: [/\.wmd$/] },
        { title: "Microsoft Windows Media Player Playlist", MIME: "application/vnd.ms-wpl", extensions: [/\.wpl$/] },
        { title: "Microsoft Windows Media Player Skin Package", MIME: "application/x-ms-wmz", extensions: [/\.wmz$/] },
        { title: "Microsoft Windows Media Video", MIME: "video/x-ms-wmv", extensions: [/\.wmv$/] },
        { title: "Microsoft Windows Media Video Playlist", MIME: "video/x-ms-wvx", extensions: [/\.wvx$/] },
        { title: "Microsoft Windows Metafile", MIME: "application/x-msmetafile", extensions: [/\.wmf$/] },
        { title: "Microsoft Windows Terminal Services", MIME: "application/x-msterminal", extensions: [/\.trm$/] },
        { title: "Microsoft Word", MIME: "application/msword", extensions: [/\.doc$/] },
        { title: "Microsoft Wordpad", MIME: "application/x-mswrite", extensions: [/\.wri$/] },
        { title: "Microsoft Works", MIME: "application/vnd.ms-works", extensions: [/\.wps$/] },
        { title: "Microsoft XAML Browser Application", MIME: "application/x-ms-xbap", extensions: [/\.xbap$/] },
        { title: "Microsoft XML Paper Specification", MIME: "application/vnd.ms-xpsdocument", extensions: [/\.xps$/] },
        { title: "MIDI - Musical Instrument Digital Interface", MIME: "audio/midi", extensions: [/\.mid$/] },
        { title: "MiniPay", MIME: "application/vnd.ibm.minipay", extensions: [/\.mpy$/] },
        { title: "MO:DCA-P", MIME: "application/vnd.ibm.modcap", extensions: [/\.afp$/] },
        { title: "Mobile Information Device Profile", MIME: "application/vnd.jcp.javame.midlet-rms", extensions: [/\.rms$/] },
        { title: "MobileTV", MIME: "application/vnd.tmobile-livetv", extensions: [/\.tmo$/] },
        { title: "Mobipocket", MIME: "application/x-mobipocket-ebook", extensions: [/\.prc$/] },
        { title: "Mobius Management Systems - Basket file", MIME: "application/vnd.mobius.mbk", extensions: [/\.mbk$/] },
        { title: "Mobius Management Systems - Distribution Database", MIME: "application/vnd.mobius.dis", extensions: [/\.dis$/] },
        { title: "Mobius Management Systems - Policy Definition Language File", MIME: "application/vnd.mobius.plc", extensions: [/\.plc$/] },
        { title: "Mobius Management Systems - Query File", MIME: "application/vnd.mobius.mqy", extensions: [/\.mqy$/] },
        { title: "Mobius Management Systems - Script Language", MIME: "application/vnd.mobius.msl", extensions: [/\.msl$/] },
        { title: "Mobius Management Systems - Topic Index File", MIME: "application/vnd.mobius.txf", extensions: [/\.txf$/] },
        { title: "Mobius Management Systems - UniversalArchive", MIME: "application/vnd.mobius.daf", extensions: [/\.daf$/] },
        { title: "mod_fly / fly.cgi", MIME: "text/vnd.fly", extensions: [/\.fly$/] },
        { title: "Mophun Certificate", MIME: "application/vnd.mophun.certificate", extensions: [/\.mpc$/] },
        { title: "Mophun VM", MIME: "application/vnd.mophun.application", extensions: [/\.mpn$/] },
        { title: "Motion JPEG 2000", MIME: "video/mj2", extensions: [/\.mj2$/] },
        { title: "MPEG Audio", MIME: "audio/mpeg", extensions: [/\.mpga$/] },
        { title: "MPEG Url", MIME: "video/vnd.mpegurl", extensions: [/\.mxu$/] },
        { title: "MPEG Video", MIME: "video/mpeg", extensions: [/\.mpeg$/] },
        { title: "MPEG-21", MIME: "application/mp21", extensions: [/\.m21$/] },
        { title: "MPEG-4 Audio", MIME: "audio/mp4", extensions: [/\.mp4a$/] },
        { title: "MPEG-4 Video", MIME: "video/mp4", extensions: [/\.mp4$/] },
        { title: "MPEG4", MIME: "application/mp4", extensions: [/\.mp4$/] },
        { title: "Multimedia Playlist Unicode", MIME: "application/vnd.apple.mpegurl", extensions: [/\.m3u8$/] },
        { title: "MUsical Score Interpreted Code Invented for the ASCII designation of Notation", MIME: "application/vnd.musician", extensions: [/\.mus$/] },
        { title: "Muvee Automatic Video Editing", MIME: "application/vnd.muvee.style", extensions: [/\.msty$/] },
        { title: "MXML", MIME: "application/xv+xml", extensions: [/\.mxml$/] },
        { title: "N-Gage Game Data", MIME: "application/vnd.nokia.n-gage.data", extensions: [/\.ngdat$/] },
        { title: "N-Gage Game Installer", MIME: "application/vnd.nokia.n-gage.symbian.install", extensions: [/\.n-gage$/] },
        { title: "Navigation Control file for XML (for ePub)", MIME: "application/x-dtbncx+xml", extensions: [/\.ncx$/] },
        { title: "Network Common Data Form (NetCDF)", MIME: "application/x-netcdf", extensions: [/\.nc$/] },
        { title: "neuroLanguage", MIME: "application/vnd.neurolanguage.nlu", extensions: [/\.nlu$/] },
        { title: "New Moon Liftoff/DNA", MIME: "application/vnd.dna", extensions: [/\.dna$/] },
        { title: "NobleNet Directory", MIME: "application/vnd.noblenet-directory", extensions: [/\.nnd$/] },
        { title: "NobleNet Sealer", MIME: "application/vnd.noblenet-sealer", extensions: [/\.nns$/] },
        { title: "NobleNet Web", MIME: "application/vnd.noblenet-web", extensions: [/\.nnw$/] },
        { title: "Nokia Radio Application - Preset", MIME: "application/vnd.nokia.radio-preset", extensions: [/\.rpst$/] },
        { title: "Nokia Radio Application - Preset", MIME: "application/vnd.nokia.radio-presets", extensions: [/\.rpss$/] },
        { title: "Notation3", MIME: "text/n3", extensions: [/\.n3$/] },
        { title: "Novadigm's RADIA and EDM products", MIME: "application/vnd.novadigm.edm", extensions: [/\.edm$/] },
        { title: "Novadigm's RADIA and EDM products", MIME: "application/vnd.novadigm.edx", extensions: [/\.edx$/] },
        { title: "Novadigm's RADIA and EDM products", MIME: "application/vnd.novadigm.ext", extensions: [/\.ext$/] },
        { title: "NpGraphIt", MIME: "application/vnd.flographit", extensions: [/\.gph$/] },
        { title: "Nuera ECELP 4800", MIME: "audio/vnd.nuera.ecelp4800", extensions: [/\.ecelp4800$/] },
        { title: "Nuera ECELP 7470", MIME: "audio/vnd.nuera.ecelp7470", extensions: [/\.ecelp7470$/] },
        { title: "Nuera ECELP 9600", MIME: "audio/vnd.nuera.ecelp9600", extensions: [/\.ecelp9600$/] },
        { title: "Office Document Architecture", MIME: "application/oda", extensions: [/\.oda$/] },
        { title: "Ogg", MIME: "application/ogg", extensions: [/\.ogx$/] },
        { title: "Ogg Audio", MIME: "audio/ogg", extensions: [/\.oga$/] },
        { title: "Ogg Video", MIME: "video/ogg", extensions: [/\.ogv$/] },
        { title: "OMA Download Agents", MIME: "application/vnd.oma.dd2+xml", extensions: [/\.dd2$/] },
        { title: "Open Document Text Web", MIME: "application/vnd.oasis.opendocument.text-web", extensions: [/\.oth$/] },
        { title: "Open eBook Publication Structure", MIME: "application/oebps-package+xml", extensions: [/\.opf$/] },
        { title: "Open Financial Exchange", MIME: "application/vnd.intu.qbo", extensions: [/\.qbo$/] },
        { title: "Open Office Extension", MIME: "application/vnd.openofficeorg.extension", extensions: [/\.oxt$/] },
        { title: "Open Score Format", MIME: "application/vnd.yamaha.openscoreformat", extensions: [/\.osf$/] },
        { title: "Open Web Media Project - Audio", MIME: "audio/webm", extensions: [/\.weba$/] },
        { title: "Open Web Media Project - Video", MIME: "video/webm", extensions: [/\.webm$/] },
        { title: "OpenDocument Chart", MIME: "application/vnd.oasis.opendocument.chart", extensions: [/\.odc$/] },
        { title: "OpenDocument Chart Template", MIME: "application/vnd.oasis.opendocument.chart-template", extensions: [/\.otc$/] },
        { title: "OpenDocument Database", MIME: "application/vnd.oasis.opendocument.database", extensions: [/\.odb$/] },
        { title: "OpenDocument Formula", MIME: "application/vnd.oasis.opendocument.formula", extensions: [/\.odf$/] },
        { title: "OpenDocument Formula Template", MIME: "application/vnd.oasis.opendocument.formula-template", extensions: [/\.odft$/] },
        { title: "OpenDocument Graphics", MIME: "application/vnd.oasis.opendocument.graphics", extensions: [/\.odg$/] },
        { title: "OpenDocument Graphics Template", MIME: "application/vnd.oasis.opendocument.graphics-template", extensions: [/\.otg$/] },
        { title: "OpenDocument Image", MIME: "application/vnd.oasis.opendocument.image", extensions: [/\.odi$/] },
        { title: "OpenDocument Image Template", MIME: "application/vnd.oasis.opendocument.image-template", extensions: [/\.oti$/] },
        { title: "OpenDocument Presentation", MIME: "application/vnd.oasis.opendocument.presentation", extensions: [/\.odp$/] },
        { title: "OpenDocument Presentation Template", MIME: "application/vnd.oasis.opendocument.presentation-template", extensions: [/\.otp$/] },
        { title: "OpenDocument Spreadsheet", MIME: "application/vnd.oasis.opendocument.spreadsheet", extensions: [/\.ods$/] },
        { title: "OpenDocument Spreadsheet Template", MIME: "application/vnd.oasis.opendocument.spreadsheet-template", extensions: [/\.ots$/] },
        { title: "OpenDocument Text", MIME: "application/vnd.oasis.opendocument.text", extensions: [/\.odt$/] },
        { title: "OpenDocument Text Master", MIME: "application/vnd.oasis.opendocument.text-master", extensions: [/\.odm$/] },
        { title: "OpenDocument Text Template", MIME: "application/vnd.oasis.opendocument.text-template", extensions: [/\.ott$/] },
        { title: "OpenGL Textures (KTX)", MIME: "image/ktx", extensions: [/\.ktx$/] },
        { title: "OpenOffice - Calc (Spreadsheet)", MIME: "application/vnd.sun.xml.calc", extensions: [/\.sxc$/] },
        { title: "OpenOffice - Calc Template (Spreadsheet)", MIME: "application/vnd.sun.xml.calc.template", extensions: [/\.stc$/] },
        { title: "OpenOffice - Draw (Graphics)", MIME: "application/vnd.sun.xml.draw", extensions: [/\.sxd$/] },
        { title: "OpenOffice - Draw Template (Graphics)", MIME: "application/vnd.sun.xml.draw.template", extensions: [/\.std$/] },
        { title: "OpenOffice - Impress (Presentation)", MIME: "application/vnd.sun.xml.impress", extensions: [/\.sxi$/] },
        { title: "OpenOffice - Impress Template (Presentation)", MIME: "application/vnd.sun.xml.impress.template", extensions: [/\.sti$/] },
        { title: "OpenOffice - Math (Formula)", MIME: "application/vnd.sun.xml.math", extensions: [/\.sxm$/] },
        { title: "OpenOffice - Writer (Text - HTML)", MIME: "application/vnd.sun.xml.writer", extensions: [/\.sxw$/] },
        { title: "OpenOffice - Writer (Text - HTML)", MIME: "application/vnd.sun.xml.writer.global", extensions: [/\.sxg$/] },
        { title: "OpenOffice - Writer Template (Text - HTML)", MIME: "application/vnd.sun.xml.writer.template", extensions: [/\.stw$/] },
        { title: "OpenType Font File", MIME: "application/x-font-otf", extensions: [/\.otf$/] },
        { title: "OSFPVG", MIME: "application/vnd.yamaha.openscoreformat.osfpvg+xml", extensions: [/\.osfpvg$/] },
        { title: "OSGi Deployment Package", MIME: "application/vnd.osgi.dp", extensions: [/\.dp$/] },
        { title: "PalmOS Data", MIME: "application/vnd.palm", extensions: [/\.pdb$/] },
        { title: "Pascal Source File", MIME: "text/x-pascal", extensions: [/\.p$/] },
        { title: "PawaaFILE", MIME: "application/vnd.pawaafile", extensions: [/\.paw$/] },
        { title: "PCL 6 Enhanced (Formely PCL XL)", MIME: "application/vnd.hp-pclxl", extensions: [/\.pclxl$/] },
        { title: "Pcsel eFIF File", MIME: "application/vnd.picsel", extensions: [/\.efif$/] },
        { title: "PCX Image", MIME: "image/x-pcx", extensions: [/\.pcx$/] },
        { title: "Photoshop Document", MIME: "image/vnd.adobe.photoshop", extensions: [/\.psd$/] },
        { title: "PICSRules", MIME: "application/pics-rules", extensions: [/\.prf$/] },
        { title: "PICT Image", MIME: "image/x-pict", extensions: [/\.pic$/] },
        { title: "pIRCh", MIME: "application/x-chat", extensions: [/\.chat$/] },
        { title: "PKCS #10 - Certification Request Standard", MIME: "application/pkcs10", extensions: [/\.p10$/] },
        { title: "PKCS #12 - Personal Information Exchange Syntax Standard", MIME: "application/x-pkcs12", extensions: [/\.p12$/] },
        { title: "PKCS #7 - Cryptographic Message Syntax Standard", MIME: "application/pkcs7-mime", extensions: [/\.p7m$/] },
        { title: "PKCS #7 - Cryptographic Message Syntax Standard", MIME: "application/pkcs7-signature", extensions: [/\.p7s$/] },
        { title: "PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)", MIME: "application/x-pkcs7-certreqresp", extensions: [/\.p7r$/] },
        { title: "PKCS #7 - Cryptographic Message Syntax Standard (Certificates)", MIME: "application/x-pkcs7-certificates", extensions: [/\.p7b$/] },
        { title: "PKCS #8 - Private-Key Information Syntax Standard", MIME: "application/pkcs8", extensions: [/\.p8$/] },
        { title: "PocketLearn Viewers", MIME: "application/vnd.pocketlearn", extensions: [/\.plf$/] },
        { title: "Portable Anymap Image", MIME: "image/x-portable-anymap", extensions: [/\.pnm$/] },
        { title: "Portable Bitmap Format", MIME: "image/x-portable-bitmap", extensions: [/\.pbm$/] },
        { title: "Portable Compiled Format", MIME: "application/x-font-pcf", extensions: [/\.pcf$/] },
        { title: "Portable Font Resource", MIME: "application/font-tdpfr", extensions: [/\.pfr$/] },
        { title: "Portable Game Notation (Chess Games)", MIME: "application/x-chess-pgn", extensions: [/\.pgn$/] },
        { title: "Portable Graymap Format", MIME: "image/x-portable-graymap", extensions: [/\.pgm$/] },
        { title: "Portable Network Graphics (PNG)", MIME: "image/png", extensions: [/\.png$/] },
        { title: "Portable Pixmap Format", MIME: "image/x-portable-pixmap", extensions: [/\.ppm$/] },
        { title: "Portable Symmetric Key Container", MIME: "application/pskc+xml", extensions: [/\.pskcxml$/] },
        { title: "PosML", MIME: "application/vnd.ctc-posml", extensions: [/\.pml$/] },
        { title: "PostScript", MIME: "application/postscript", extensions: [/\.ai$/] },
        { title: "PostScript Fonts", MIME: "application/x-font-type1", extensions: [/\.pfa$/] },
        { title: "PowerBuilder", MIME: "application/vnd.powerbuilder6", extensions: [/\.pbd$/] },
        { title: "Pretty Good Privacy", MIME: "application/pgp-encrypted", extensions: [/\$/] },
        { title: "Pretty Good Privacy - Signature", MIME: "application/pgp-signature", extensions: [/\.pgp$/] },
        { title: "Preview Systems ZipLock/VBox", MIME: "application/vnd.previewsystems.box", extensions: [/\.box$/] },
        { title: "Princeton Video Image", MIME: "application/vnd.pvi.ptid1", extensions: [/\.ptid$/] },
        { title: "Pronunciation Lexicon Specification", MIME: "application/pls+xml", extensions: [/\.pls$/] },
        { title: "Proprietary P&G Standard Reporting System", MIME: "application/vnd.pg.format", extensions: [/\.str$/] },
        { title: "Proprietary P&G Standard Reporting System", MIME: "application/vnd.pg.osasli", extensions: [/\.ei6$/] },
        { title: "PRS Lines Tag", MIME: "text/prs.lines.tag", extensions: [/\.dsc$/] },
        { title: "PSF Fonts", MIME: "application/x-font-linux-psf", extensions: [/\.psf$/] },
        { title: "PubliShare Objects", MIME: "application/vnd.publishare-delta-tree", extensions: [/\.qps$/] },
        { title: "Qualcomm's Plaza Mobile Internet", MIME: "application/vnd.pmi.widget", extensions: [/\.wg$/] },
        { title: "QuarkXpress", MIME: "application/vnd.quark.quarkxpress", extensions: [/\.qxd$/] },
        { title: "QUASS Stream Player", MIME: "application/vnd.epson.esf", extensions: [/\.esf$/] },
        { title: "QUASS Stream Player", MIME: "application/vnd.epson.msf", extensions: [/\.msf$/] },
        { title: "QUASS Stream Player", MIME: "application/vnd.epson.ssf", extensions: [/\.ssf$/] },
        { title: "QuickAnime Player", MIME: "application/vnd.epson.quickanime", extensions: [/\.qam$/] },
        { title: "Quicken", MIME: "application/vnd.intu.qfx", extensions: [/\.qfx$/] },
        { title: "Quicktime Video", MIME: "video/quicktime", extensions: [/\.qt$/] },
        { title: "RAR Archive", MIME: "application/x-rar-compressed", extensions: [/\.rar$/] },
        { title: "Real Audio Sound", MIME: "audio/x-pn-realaudio", extensions: [/\.ram$/] },
        { title: "Real Audio Sound", MIME: "audio/x-pn-realaudio-plugin", extensions: [/\.rmp$/] },
        { title: "Really Simple Discovery", MIME: "application/rsd+xml", extensions: [/\.rsd$/] },
        { title: "RealMedia", MIME: "application/vnd.rn-realmedia", extensions: [/\.rm$/] },
        { title: "RealVNC", MIME: "application/vnd.realvnc.bed", extensions: [/\.bed$/] },
        { title: "Recordare Applications", MIME: "application/vnd.recordare.musicxml", extensions: [/\.mxl$/] },
        { title: "Recordare Applications", MIME: "application/vnd.recordare.musicxml+xml", extensions: [/\.musicxml$/] },
        { title: "Relax NG Compact Syntax", MIME: "application/relax-ng-compact-syntax", extensions: [/\.rnc$/] },
        { title: "RemoteDocs R-Viewer", MIME: "application/vnd.data-vision.rdz", extensions: [/\.rdz$/] },
        { title: "Resource Description Framework", MIME: "application/rdf+xml", extensions: [/\.rdf$/] },
        { title: "RetroPlatform Player", MIME: "application/vnd.cloanto.rp9", extensions: [/\.rp9$/] },
        { title: "RhymBox", MIME: "application/vnd.jisp", extensions: [/\.jisp$/] },
        { title: "Rich Text Format", MIME: "application/rtf", extensions: [/\.rtf$/] },
        { title: "Rich Text Format (RTF)", MIME: "text/richtext", extensions: [/\.rtx$/] },
        { title: "ROUTE 66 Location Based Services", MIME: "application/vnd.route66.link66+xml", extensions: [/\.link66$/] },
        { title: "RSS - Really Simple Syndication", MIME: "application/rss+xml", extensions: [/\.rss$/] },
        { title: "S Hexdump Format", MIME: "application/shf+xml", extensions: [/\.shf$/] },
        { title: "SailingTracker", MIME: "application/vnd.sailingtracker.track", extensions: [/\.st$/] },
        { title: "Scalable Vector Graphics (SVG)", MIME: "image/svg+xml", extensions: [/\.svg$/] },
        { title: "ScheduleUs", MIME: "application/vnd.sus-calendar", extensions: [/\.sus$/] },
        { title: "Search/Retrieve via URL Response Format", MIME: "application/sru+xml", extensions: [/\.sru$/] },
        { title: "Secure Electronic Transaction - Payment", MIME: "application/set-payment-initiation", extensions: [/\.setpay$/] },
        { title: "Secure Electronic Transaction - Registration", MIME: "application/set-registration-initiation", extensions: [/\.setreg$/] },
        { title: "Secured eMail", MIME: "application/vnd.sema", extensions: [/\.sema$/] },
        { title: "Secured eMail", MIME: "application/vnd.semd", extensions: [/\.semd$/] },
        { title: "Secured eMail", MIME: "application/vnd.semf", extensions: [/\.semf$/] },
        { title: "SeeMail", MIME: "application/vnd.seemail", extensions: [/\.see$/] },
        { title: "Server Normal Format", MIME: "application/x-font-snf", extensions: [/\.snf$/] },
        { title: "Server-Based Certificate Validation Protocol - Validation Policies - Request", MIME: "application/scvp-vp-request", extensions: [/\.spq$/] },
        { title: "Server-Based Certificate Validation Protocol - Validation Policies - Response", MIME: "application/scvp-vp-response", extensions: [/\.spp$/] },
        { title: "Server-Based Certificate Validation Protocol - Validation Request", MIME: "application/scvp-cv-request", extensions: [/\.scq$/] },
        { title: "Server-Based Certificate Validation Protocol - Validation Response", MIME: "application/scvp-cv-response", extensions: [/\.scs$/] },
        { title: "Session Description Protocol", MIME: "application/sdp", extensions: [/\.sdp$/] },
        { title: "Setext", MIME: "text/x-setext", extensions: [/\.etx$/] },
        { title: "SGI Movie", MIME: "video/x-sgi-movie", extensions: [/\.movie$/] },
        { title: "Shana Informed Filler", MIME: "application/vnd.shana.informed.formdata", extensions: [/\.ifm$/] },
        { title: "Shana Informed Filler", MIME: "application/vnd.shana.informed.formtemplate", extensions: [/\.itp$/] },
        { title: "Shana Informed Filler", MIME: "application/vnd.shana.informed.interchange", extensions: [/\.iif$/] },
        { title: "Shana Informed Filler", MIME: "application/vnd.shana.informed.package", extensions: [/\.ipk$/] },
        { title: "Sharing Transaction Fraud Data", MIME: "application/thraud+xml", extensions: [/\.tfi$/] },
        { title: "Shell Archive", MIME: "application/x-shar", extensions: [/\.shar$/] },
        { title: "Silicon Graphics RGB Bitmap", MIME: "image/x-rgb", extensions: [/\.rgb$/] },
        { title: "SimpleAnimeLite Player", MIME: "application/vnd.epson.salt", extensions: [/\.slt$/] },
        { title: "Simply Accounting", MIME: "application/vnd.accpac.simply.aso", extensions: [/\.aso$/] },
        { title: "Simply Accounting - Data Import", MIME: "application/vnd.accpac.simply.imp", extensions: [/\.imp$/] },
        { title: "SimTech MindMapper", MIME: "application/vnd.simtech-mindmapper", extensions: [/\.twd$/] },
        { title: "Sixth Floor Media - CommonSpace", MIME: "application/vnd.commonspace", extensions: [/\.csp$/] },
        { title: "SMAF Audio", MIME: "application/vnd.yamaha.smaf-audio", extensions: [/\.saf$/] },
        { title: "SMAF File", MIME: "application/vnd.smaf", extensions: [/\.mmf$/] },
        { title: "SMAF Phrase", MIME: "application/vnd.yamaha.smaf-phrase", extensions: [/\.spf$/] },
        { title: "SMART Technologies Apps", MIME: "application/vnd.smart.teacher", extensions: [/\.teacher$/] },
        { title: "SourceView Document", MIME: "application/vnd.svd", extensions: [/\.svd$/] },
        { title: "SPARQL - Query", MIME: "application/sparql-query", extensions: [/\.rq$/] },
        { title: "SPARQL - Results", MIME: "application/sparql-results+xml", extensions: [/\.srx$/] },
        { title: "Speech Recognition Grammar Specification", MIME: "application/srgs", extensions: [/\.gram$/] },
        { title: "Speech Recognition Grammar Specification - XML", MIME: "application/srgs+xml", extensions: [/\.grxml$/] },
        { title: "Speech Synthesis Markup Language", MIME: "application/ssml+xml", extensions: [/\.ssml$/] },
        { title: "SSEYO Koan Play File", MIME: "application/vnd.koan", extensions: [/\.skp$/] },
        { title: "Standard Generalized Markup Language (SGML)", MIME: "text/sgml", extensions: [/\.sgml$/] },
        { title: "StarOffice - Calc", MIME: "application/vnd.stardivision.calc", extensions: [/\.sdc$/] },
        { title: "StarOffice - Draw", MIME: "application/vnd.stardivision.draw", extensions: [/\.sda$/] },
        { title: "StarOffice - Impress", MIME: "application/vnd.stardivision.impress", extensions: [/\.sdd$/] },
        { title: "StarOffice - Math", MIME: "application/vnd.stardivision.math", extensions: [/\.smf$/] },
        { title: "StarOffice - Writer", MIME: "application/vnd.stardivision.writer", extensions: [/\.sdw$/] },
        { title: "StarOffice - Writer (Global)", MIME: "application/vnd.stardivision.writer-global", extensions: [/\.sgl$/] },
        { title: "StepMania", MIME: "application/vnd.stepmania.stepchart", extensions: [/\.sm$/] },
        { title: "Stuffit Archive", MIME: "application/x-stuffit", extensions: [/\.sit$/] },
        { title: "Stuffit Archive", MIME: "application/x-stuffitx", extensions: [/\.sitx$/] },
        { title: "SudokuMagic", MIME: "application/vnd.solent.sdkm+xml", extensions: [/\.sdkm$/] },
        { title: "Sugar Linux Application Bundle", MIME: "application/vnd.olpc-sugar", extensions: [/\.xo$/] },
        { title: "Sun Audio - Au file format", MIME: "audio/basic", extensions: [/\.au$/] },
        { title: "SundaHus WQ", MIME: "application/vnd.wqd", extensions: [/\.wqd$/] },
        { title: "Symbian Install Package", MIME: "application/vnd.symbian.install", extensions: [/\.sis$/] },
        { title: "Synchronized Multimedia Integration Language", MIME: "application/smil+xml", extensions: [/\.smi$/] },
        { title: "SyncML", MIME: "application/vnd.syncml+xml", extensions: [/\.xsm$/] },
        { title: "SyncML - Device Management", MIME: "application/vnd.syncml.dm+wbxml", extensions: [/\.bdm$/] },
        { title: "SyncML - Device Management", MIME: "application/vnd.syncml.dm+xml", extensions: [/\.xdm$/] },
        { title: "System V Release 4 CPIO Archive", MIME: "application/x-sv4cpio", extensions: [/\.sv4cpio$/] },
        { title: "System V Release 4 CPIO Checksum Data", MIME: "application/x-sv4crc", extensions: [/\.sv4crc$/] },
        { title: "Systems Biology Markup Language", MIME: "application/sbml+xml", extensions: [/\.sbml$/] },
        { title: "Tab Seperated Values", MIME: "text/tab-separated-values", extensions: [/\.tsv$/] },
        { title: "Tagged Image File Format", MIME: "image/tiff", extensions: [/\.tiff$/] },
        { title: "Tao Intent", MIME: "application/vnd.tao.intent-module-archive", extensions: [/\.tao$/] },
        { title: "Tar File (Tape Archive)", MIME: "application/x-tar", extensions: [/\.tar$/] },
        { title: "Tcl Script", MIME: "application/x-tcl", extensions: [/\.tcl$/] },
        { title: "TeX", MIME: "application/x-tex", extensions: [/\.tex$/] },
        { title: "TeX Font Metric", MIME: "application/x-tex-tfm", extensions: [/\.tfm$/] },
        { title: "Text Encoding and Interchange", MIME: "application/tei+xml", extensions: [/\.tei$/] },
        { title: "Text File", MIME: "text/plain", extensions: [/\.txt$/] },
        { title: "TIBCO Spotfire", MIME: "application/vnd.spotfire.dxp", extensions: [/\.dxp$/] },
        { title: "TIBCO Spotfire", MIME: "application/vnd.spotfire.sfs", extensions: [/\.sfs$/] },
        { title: "Time Stamped Data Envelope", MIME: "application/timestamped-data", extensions: [/\.tsd$/] },
        { title: "TRI Systems Config", MIME: "application/vnd.trid.tpt", extensions: [/\.tpt$/] },
        { title: "Triscape Map Explorer", MIME: "application/vnd.triscape.mxs", extensions: [/\.mxs$/] },
        { title: "troff", MIME: "text/troff", extensions: [/\.t$/] },
        { title: "True BASIC", MIME: "application/vnd.trueapp", extensions: [/\.tra$/] },
        { title: "TrueType Font", MIME: "application/x-font-ttf", extensions: [/\.ttf$/] },
        { title: "Turtle (Terse RDF Triple Language)", MIME: "text/turtle", extensions: [/\.ttl$/] },
        { title: "UMAJIN", MIME: "application/vnd.umajin", extensions: [/\.umj$/] },
        { title: "Unique Object Markup Language", MIME: "application/vnd.uoml+xml", extensions: [/\.uoml$/] },
        { title: "Unity 3d", MIME: "application/vnd.unity", extensions: [/\.unityweb$/] },
        { title: "Universal Forms Description Language", MIME: "application/vnd.ufdl", extensions: [/\.ufd$/] },
        { title: "URI Resolution Services", MIME: "text/uri-list", extensions: [/\.uri$/] },
        { title: "User Interface Quartz - Theme (Symbian)", MIME: "application/vnd.uiq.theme", extensions: [/\.utz$/] },
        { title: "Ustar (Uniform Standard Tape Archive)", MIME: "application/x-ustar", extensions: [/\.ustar$/] },
        { title: "UUEncode", MIME: "text/x-uuencode", extensions: [/\.uu$/] },
        { title: "vCalendar", MIME: "text/x-vcalendar", extensions: [/\.vcs$/] },
        { title: "vCard", MIME: "text/x-vcard", extensions: [/\.vcf$/] },
        { title: "Video CD", MIME: "application/x-cdlink", extensions: [/\.vcd$/] },
        { title: "Viewport+", MIME: "application/vnd.vsf", extensions: [/\.vsf$/] },
        { title: "Virtual Reality Modeling Language", MIME: "model/vrml", extensions: [/\.wrl$/] },
        { title: "VirtualCatalog", MIME: "application/vnd.vcx", extensions: [/\.vcx$/] },
        { title: "Virtue MTS", MIME: "model/vnd.mts", extensions: [/\.mts$/] },
        { title: "Virtue VTU", MIME: "model/vnd.vtu", extensions: [/\.vtu$/] },
        { title: "Visionary", MIME: "application/vnd.visionary", extensions: [/\.vis$/] },
        { title: "Vivo", MIME: "video/vnd.vivo", extensions: [/\.viv$/] },
        { title: "Voice Browser Call Control", MIME: "application/ccxml+xml,", extensions: [/\.ccxml$/] },
        { title: "VoiceXML", MIME: "application/voicexml+xml", extensions: [/\.vxml$/] },
        { title: "WAIS Source", MIME: "application/x-wais-source", extensions: [/\.src$/] },
        { title: "WAP Binary XML (WBXML)", MIME: "application/vnd.wap.wbxml", extensions: [/\.wbxml$/] },
        { title: "WAP Bitamp (WBMP)", MIME: "image/vnd.wap.wbmp", extensions: [/\.wbmp$/] },
        { title: "Waveform Audio File Format (WAV)", MIME: "audio/x-wav", extensions: [/\.wav$/] },
        { title: "Web Distributed Authoring and Versioning", MIME: "application/davmount+xml", extensions: [/\.davmount$/] },
        { title: "Web Open Font Format", MIME: "application/x-font-woff", extensions: [/\.woff$/] },
        { title: "Web Services Policy", MIME: "application/wspolicy+xml", extensions: [/\.wspolicy$/] },
        { title: "WebP Image", MIME: "image/webp", extensions: [/\.webp$/] },
        { title: "WebTurbo", MIME: "application/vnd.webturbo", extensions: [/\.wtb$/] },
        { title: "Widget Packaging and XML Configuration", MIME: "application/widget", extensions: [/\.wgt$/] },
        { title: "WinHelp", MIME: "application/winhlp", extensions: [/\.hlp$/] },
        { title: "Wireless Markup Language (WML)", MIME: "text/vnd.wap.wml", extensions: [/\.wml$/] },
        { title: "Wireless Markup Language Script (WMLScript)", MIME: "text/vnd.wap.wmlscript", extensions: [/\.wmls$/] },
        { title: "WMLScript", MIME: "application/vnd.wap.wmlscriptc", extensions: [/\.wmlsc$/] },
        { title: "Wordperfect", MIME: "application/vnd.wordperfect", extensions: [/\.wpd$/] },
        { title: "Worldtalk", MIME: "application/vnd.wt.stf", extensions: [/\.stf$/] },
        { title: "WSDL - Web Services Description Language", MIME: "application/wsdl+xml", extensions: [/\.wsdl$/] },
        { title: "X BitMap", MIME: "image/x-xbitmap", extensions: [/\.xbm$/] },
        { title: "X PixMap", MIME: "image/x-xpixmap", extensions: [/\.xpm$/] },
        { title: "X Window Dump", MIME: "image/x-xwindowdump", extensions: [/\.xwd$/] },
        { title: "X.509 Certificate", MIME: "application/x-x509-ca-cert", extensions: [/\.der$/] },
        { title: "Xfig", MIME: "application/x-xfig", extensions: [/\.fig$/] },
        { title: "XHTML - The Extensible HyperText Markup Language", MIME: "application/xhtml+xml", extensions: [/\.xhtml$/] },
        { title: "XML - Extensible Markup Language", MIME: "application/xml", extensions: [/\.xml$/] },
        { title: "XML Configuration Access Protocol - XCAP Diff", MIME: "application/xcap-diff+xml", extensions: [/\.xdf$/] },
        { title: "XML Encryption Syntax and Processing", MIME: "application/xenc+xml", extensions: [/\.xenc$/] },
        { title: "XML Patch Framework", MIME: "application/patch-ops-error+xml", extensions: [/\.xer$/] },
        { title: "XML Resource Lists", MIME: "application/resource-lists+xml", extensions: [/\.rl$/] },
        { title: "XML Resource Lists", MIME: "application/rls-services+xml", extensions: [/\.rs$/] },
        { title: "XML Resource Lists Diff", MIME: "application/resource-lists-diff+xml", extensions: [/\.rld$/] },
        { title: "XML Transformations", MIME: "application/xslt+xml", extensions: [/\.xslt$/] },
        { title: "XML-Binary Optimized Packaging", MIME: "application/xop+xml", extensions: [/\.xop$/] },
        { title: "XPInstall - Mozilla", MIME: "application/x-xpinstall", extensions: [/\.xpi$/] },
        { title: "XSPF - XML Shareable Playlist Format", MIME: "application/xspf+xml", extensions: [/\.xspf$/] },
        { title: "XUL - XML User Interface Language", MIME: "application/vnd.mozilla.xul+xml", extensions: [/\.xul$/] },
        { title: "XYZ File Format", MIME: "chemical/x-xyz", extensions: [/\.xyz$/] },
        { title: "YAML Ain't Markup Language / Yet Another Markup Language", MIME: "text/yaml", extensions: [/\.yaml$/] },
        { title: "YANG Data Modeling Language", MIME: "application/yang", extensions: [/\.yang$/] },
        { title: "YIN (YANG - XML)", MIME: "application/yin+xml", extensions: [/\.yin$/] },
        { title: "Z.U.L. Geometry", MIME: "application/vnd.zul", extensions: [/\.zir$/] },
        { title: "Zip Archive", MIME: "application/zip", extensions: [/\.zip$/] },
        { title: "ZVUE Media Manager", MIME: "application/vnd.handheld-entertainment+xml", extensions: [/\.zmm$/] },
        { title: "Zzazz Deck", MIME: "application/vnd.zzazz.deck+xml", extensions: [/\.zaz$/] }
    ];
})(mime = exports.mime || (exports.mime = {}));
//# sourceMappingURL=mime.js.map