"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
//Client file generated by RPC Compiler.
var core_1 = require('@angular/core');
var http_1 = require('@angular/http');
var Observable_1 = require('rxjs/Observable');
var Serializable_1 = require('Serializable');
require('rxjs/add/operator/map');
require('rxjs/add/operator/catch');
var Demo = (function () {
    function Demo($_Angular2HttpClient) {
        this.$_Angular2HttpClient = $_Angular2HttpClient;
    }
    Demo.prototype.Dogs = function () {
        var _this = this;
        return Observable_1.Observable.create(function (observer) {
            _this.$_Angular2HttpClient.post('/rpc/demo.rpc.js?Demo-Dogs', []).map(Serializable_1.Converter.convertStringResponse).subscribe(function (stringValue) {
                console.log("stringValue: ", stringValue);
                if (stringValue) {
                    var jsonObject = JSON.parse(stringValue);
                    Serializable_1.Deserialize(jsonObject, function (deserialized) {
                        observer.next(deserialized);
                        observer.complete();
                    });
                }
                else {
                    observer.next(null);
                    observer.complete();
                }
            });
        });
    };
    Demo.prototype.test = function (jack, sam, jason) {
        return this.$_Angular2HttpClient.post('/rpc/demo.rpc.js?Demo-test', [jack, sam, jason]).map(Serializable_1.Converter.convertStringResponse);
    };
    Demo.prototype.tom = function () {
        var _this = this;
        return Observable_1.Observable.create(function (observer) {
            _this.$_Angular2HttpClient.post('/rpc/demo.rpc.js?Demo-tom', []).map(Serializable_1.Converter.convertStringResponse).subscribe(function (stringValue) {
                console.log("stringValue: ", stringValue);
                if (stringValue) {
                    var jsonObject = JSON.parse(stringValue);
                    Serializable_1.Deserialize(jsonObject, function (deserialized) {
                        observer.next(deserialized);
                        observer.complete();
                    });
                }
                else {
                    observer.next(null);
                    observer.complete();
                }
            });
        });
    };
    Demo.prototype.jerry = function () {
        return this.$_Angular2HttpClient.post('/rpc/demo.rpc.js?Demo-jerry', []).map(Serializable_1.Converter.convertBooleanResponse);
    };
    Demo = __decorate([
        core_1.Injectable(), 
        __metadata('design:paramtypes', [http_1.Http])
    ], Demo);
    return Demo;
}());
exports.Demo = Demo;
//# sourceMappingURL=demo.client.js.map